# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sys
from EEG import eeg_data, print_plots, welch_data, band_graph, print_psd

day1 = "chb01_01.edf" #no seizure
day2 = "chb01_02.edf" #no seizure
day3 = "chb01_03.edf" #seizure
day4 = "chb01_04.edf" #seizure
day5 = "chb01_05.edf" #no seizure
day15 = "chb01_15.edf" #seizure


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.No_seizure = QtWidgets.QComboBox(self.centralwidget)
        self.No_seizure.setGeometry(QtCore.QRect(80, 370, 91, 21))
        self.No_seizure.setObjectName("No_seizure")
        self.No_seizure.addItem("No Seizure", ['day1', 'day2', 'day5'])
        self.No_seizure.addItem("Seizure", ['day3', 'day4', 'day15'])
        self.plotContainer = QtWidgets.QFrame(self.centralwidget)
        self.plotContainer.setGeometry(QtCore.QRect(50, 30, 691, 321))
        self.plotContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotContainer.setObjectName("plotContainer")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.plotContainer)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 691, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.psd = QtWidgets.QPushButton(self.centralwidget)
        self.psd.setGeometry(QtCore.QRect(400, 370, 75, 23))
        self.psd.setObjectName("psd")
        self.bandPower = QtWidgets.QPushButton(self.centralwidget)
        self.bandPower.setGeometry(QtCore.QRect(400, 430, 75, 23))
        self.bandPower.setObjectName("bandPower")
        self.eeg_plots = QtWidgets.QPushButton(self.centralwidget)
        self.eeg_plots.setGeometry(QtCore.QRect(400, 490, 75, 23))
        self.eeg_plots.setObjectName("eeg_plots")
        self.dayCombo = QtWidgets.QComboBox(self.centralwidget)
        self.dayCombo.setGeometry(QtCore.QRect(180, 370, 69, 22))
        self.dayCombo.setObjectName("dayCombo")
        self.dayCombo.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.No_seizure.currentIndexChanged.connect(self.update_days)

    
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.No_seizure.setItemText(0, _translate("MainWindow", "No Seizure"))
        self.No_seizure.setItemText(1, _translate("MainWindow", "Seizure"))
        self.psd.setText(_translate("MainWindow", "PSD"))
        self.bandPower.setText(_translate("MainWindow", "Band Power"))
        self.eeg_plots.setText(_translate("MainWindow", "EEG plots"))
        #self.dayCombo.setItemText(0, _translate("MainWindow", "day"))

    def update_days(self, index):
        days = self.No_seizure.itemData(index)
        self.dayCombo.clear()
        for day in days:
            self.dayCombo.addItem(day)

    def set_file(self):
        selection = self.No_seizure.currentText()
        if selection in ["No Seizure", "Seizure"]:
            day_selected = self.dayCombo.currentText()
            if day_selected == "day1":
                self.eeg = eeg_data(day1)
                self.band_powers = welch_data(self.eeg[1], self.eeg[2])
            elif day_selected == "day2":
                self.eeg = eeg_data(day2)
                self.band_powers = welch_data(self.eeg[1], self.eeg[2])
            elif day_selected == "day3":
                self.eeg = eeg_data(day3)
                self.band_powers = welch_data(self.eeg[1], self.eeg[2])
            elif day_selected == "day4":
                self.eeg = eeg_data(day4)
                self.band_powers = welch_data(self.eeg[1], self.eeg[2])
            elif day_selected == "day5":
                self.eeg = eeg_data(day5)
                self.band_powers = welch_data(self.eeg[1], self.eeg[2])
            elif day_selected == "day15":
                self.eeg = eeg_data(day15)
                self.band_powers = welch_data(self.eeg[1], self.eeg[2])
            
    

    def connect_signals(self):
        self.No_seizure.currentIndexChanged.connect(self.set_file)
        self.dayCombo.currentIndexChanged.connect(self.set_file)

    
    def connect_buttons(self):
        self.psd.clicked.connect(lambda: print_psd(self.eeg[1]))
        self.bandPower.clicked.connect(lambda: band_graph(self.band_powers))
        self.eeg_plots.clicked.connect(lambda: print_plots(self.eeg[1]))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.set_file()
    ui.connect_buttons()
    ui.connect_signals()
    MainWindow.show()
    sys.exit(app.exec_())



